# Generated by Django 6.0 on 2025-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artciels',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
