# Generated by Django 6.0 on 2025-12-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_artciels_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artciels',
            name='image',
        ),
    ]
