# Generated by Django 6.0 on 2025-12-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_remove_artciels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artciels',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
