# Generated by Django 6.0 on 2025-12-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_artciels_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
