# Generated by Django 6.0 on 2025-12-24 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artciels',
            name='news_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='News.category'),
        ),
    ]
