# Generated by Django 6.0 on 2025-12-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artciels',
            name='visble',
            field=models.BooleanField(default=True),
        ),
    ]
