# Generated by Django 5.2.8 on 2026-01-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0009_artciels_visble"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="visble",
            field=models.BooleanField(default=True),
        ),
    ]
